FROM nginx:latest

WORKDIR /usr/share/nginx/html

RUN apt update
RUN apt install git -y
RUN rm -rf ./*

# Pour faire l'équivalent des trois dernières commandes d'un coup
RUN git clone https://github.com/withaarzoo/3D-Rotate-Tube .

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ] 